# Generated by Django 3.2.23 on 2024-01-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0002_auto_20240109_1555'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopDetails',
        ),
    ]
