# Generated by Django 3.2.23 on 2024-01-09 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_gst', models.CharField(max_length=100)),
                ('local_address', models.CharField(max_length=200)),
                ('dist', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=200)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='listproduct',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venders.shopdetails', to_field='email'),
        ),
    ]
