# Generated by Django 3.2.23 on 2024-01-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0003_auto_20240116_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(default='un_category', max_length=30, verbose_name=[('---', '----------'), ('PHONE', 'PHONE'), ('LAPTOP', 'LAPTOP')]),
        ),
    ]
