# Generated by Django 3.2.23 on 2024-01-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venders', '0004_alter_productcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('---', '----------'), ('PHONE', 'PHONE'), ('LAPTOP', 'LAPTOP')], default='un_category', max_length=30),
        ),
    ]
